### ISSUE TITLE
[REQ] Function to disable pursuit AI

### ISSUE THREAD

**Issue by bmk-dev** [LMSDev/LSPDFR-API#1]
A function to disable LSPDFR taking over the AI of peds added to a pursuit would be great. That way, we could have peds in a pursuit, so backup still recognizes them as a suspect, but we can also control their AI and make them do things such as fight back, rather than always flee.

**Comment by Albo1125** [comment]
I think the following kind of ties in with this.
I'd like to request an option to set the resistance level of a ped: in other words, I would like to control how they react when getting arrested. I sometimes want to be able to make them comply and put their hands up, but sometimes I'd like them to ignore the player and keep doing what they are without having a pursuit initiated, e.g. keep shooting the playerPed and not just stop that and put their hands up. I'd also like the option to have them run and have a pursuit created (what sometimes randomly happens at the moment).
I hope I've been clear in conveying this. Thanks!
