### ISSUE TITLE
[REQ] Ability to put a ped into a 'stopped' state

### ISSUE THREAD

**Issue by Stealth22PD** [LMSDev/LSPDFR-API#13]
Let's start using this Git repo again! =P

I'm not sure if there's already a way to do this programmatically, but it would be nice if there was a function we could call that would put a ped into that 'stopped' state where you can interact with them. Like when you hold 'E' to stop a ped, or when you ask a driver to step out of their vehicle. You can either interact (ask for ID/cite/warn) with them by pressing 'E', or place them under arrest by holding 'E'.

Can we have a function that would do this? I found **SetPedAsArrested(Rage.Ped)** in the API namespace, but I don't think that does the same thing, based on the name of the function. (I haven't tried it yet, though.)

@LMSDev?

**Comment by Albo1125** [comment]
I agree!
It would also be nice to be able to force them **out** of a stopped state (e.g. for my Taxi/Follow features).

**Comment by Albo1125** [comment]
A function like SetPedAsStopped(Ped ped, bool stopped) is something I'd really like to see.

**Comment by stackrainbow** [comment]
Looks like LMS has implemented this and it may make it's way into a future release.
