### ISSUE TITLE
Ability to sync LSPDFR with the LSPDFR web page

### ISSUE THREAD

**Issue by EliteOperations** [LMSDev/LSPDFR-API#19]
One prime example would be the GTA IV Key sync, which enabled users to view their statistics once something is done. (ie. tracking of the number of arrests,citations, most patrolled area, etc....). With this enabled, once multiplayer clans start to become common, users will be able to share their statistics to determine if they're fit for the clan itself.

**Comment by LukeD7** [comment]
I don't recall the reason why but the crime statistics system that used to exist was taken down.

AFAIK (and from a quick forum search) it's planned to return for LSPDFR, however there is a lot in the pipeline to be done and not a lot of time available. So don't hold your breath.

Also labelling this as request :)

**Comment by stackrainbow** [comment]
We're hoping to include this for the next release or possibly the release after if we don't get time.

However, this page isn't really for general requests, only requests with the API.
