### ISSUE TITLE
Ability to get currently running callout name

### ISSUE THREAD

**Issue by AnIdioticMonkey** [LMSDev/LSPDFR-API#20]
The ability to get the current callout's name would be very helpful, especially to me at the moment. Right now i am comparing the class created (read from the RPH log), however it is a workaround and very ugly, especially when it could simply be Functions.GetCurrentCalloutName(get;) 

Hopefully you decide to make my life easier :)

Thanks.

**Comment by Bluscream** [comment]
@AnIdioticMonkey can you share your current method?

**Comment by stackrainbow** [comment]
This has been implemented internally by LMS and may make it's way into a future version.

**Comment by Bluscream** [comment]
Can you add a milestone? So we see which version will have it shipped?
