### ISSUE TITLE
[REQ] Function to get/set vehicle info

### ISSUE THREAD

**Issue by bmk-dev** [LMSDev/LSPDFR-API#3]
A function to grab vehicle info, for use in things like my speed radar, or FinKone's plate checker, would be extremely useful.

_Requested to put this here so LMS doesn't forget_

**Comment by Stealth22PD** [comment]
It would be nice to able to SET the registration info as well.

http://www.lcpdfr.com/forums/topic/53217-registered-owner-of-a-spawned-vehicle/
