### ISSUE TITLE
[BUG] Peds don't respond to commands when Persona is set

### ISSUE THREAD

**Issue by Stealth22PD** [LMSDev/LSPDFR-API#6]
Posting this as a reminder for LMS, from this thread: http://www.lcpdfr.com/forums/topic/53351-peds-ignore-lspd-when-their-persona-is-set

LMS, I added the Acknowledged label, as you acknowledged this on the forums as a bug.

**Comment by bmk-dev** [comment]
The Acknowledged label is only to be added by LSPDFR staff once they have acknowledged the issue. :P

EDIT: Just saw the last line, sorry lmao.
