### ISSUE TITLE
[CLOSED] Detect when a callout is active

### ISSUE THREAD

**Issue by Stealth22PD** [LMSDev/LSPDFR-API#8]
This is sort of an extension on issue #2, but I thought it deserved it's own request.

Could we have a function (returning a bool) which would tell us if a callout is currently active?

**Comment by LukeD7** [comment]
You mean like Functions.IsCalloutRunning()? Or do you mean when a callout is accepted?

**Comment by Stealth22PD** [comment]
What the...how in the **_hell**_ did I miss that?!

I must have been really sleepy or something when I was looking at the API...

Never mind, I'll see myself out. =P
